decomp: `generic-obs`
water111/jak-project pull request #894
Opened 2021-10-11 22:31 UTC by xTVaser

also up for visibility -- pretty old file so transferring everything over to the new state system.

2021-11-12 16:33 UTC, ManDude commented on decompiler/config/all-types.gc
> +(define-extern command-get-trans (function pair vector vector))
These don't actually take pairs. I've seen them be called with processes and strings in their args. This should just be `object`, looks like they could put anything.

2021-11-12 22:14 UTC, ManDude commented on goal_src/engine/game/generic-obs.gc
> +  ;  (logclear! (-> self mask) (process-mask heap-shrunk))
FYI we need actually functional manipys, make this body just `(loop (suspend))` instead of `(none)`

2021-11-14 03:51 UTC, water111 commented on decompiler/config/all-types.gc
> +   (cur-event-hook       (function none)        :offset-assert 184) ;; TODO - no idea on these types
probably should return `object` but ok for now. I'd guess these are state handlers

2021-11-14 03:59 UTC, water111 requested changes
just a few types (these actually matter and will cause weird crashes if they are wrong) and I think you are accidentally changing the googletest submodule

2021-11-14 03:59 UTC, water111 commented on goal_src/engine/game/generic-obs.gc
> +  (go (the-as (state none) swingpole-stance))
is this really what the decompiler comes up with here? Something doesn't look right, maybe you still have a cast on this?

2021-11-14 03:59 UTC, water111 commented on goal_src/engine/game/generic-obs.gc
> +  (go (the-as (state none) (method-of-object obj die)))
same here

2021-11-14 03:59 UTC, water111 commented on goal_src/engine/game/generic-obs.gc
> +  (local-vars (sv-16 int))
this needs to be a `res-tag`

2021-11-14 03:59 UTC, water111 commented on goal_src/engine/game/generic-obs.gc
> +  (local-vars (sv-16 int))
this needs to be a `res-tag`

2021-11-14 04:31 UTC, merged